name: owi

services:  
  # ai web interface
  open-webui:
    restart: unless-stopped
    image: ghcr.io/open-webui/open-webui:0.5.20-cuda
    ports:
      - 8080:8080
    env_file:
      - .service.webui.env
    entrypoint:
      - bash
      - -c
      - |
        echo "Copy the default locale specific config ...."
        cp -n /app/backend/open_webui/configs/config_$${DEFAULT_LOCALE}.json /app/backend/data/config.json
        echo "Starting Open WebUI server..."
        /app/backend/start.sh &

        # Wait for Open WebUI API to become available
        echo "Waiting for Open WebUI to start..." &&
        while ! curl -s -o /dev/null "http://localhost:8080/health"; do
          sleep 2;
        done &&

        echo "Open WebUI started"

        echo "Sign up default admin user ..."
        SIGNUP_RESPONSE=$(curl -s -X POST "http://localhost:8080/api/v1/auths/signup" \
          -H "Content-Type: application/json" \
          --data-raw "{\"name\":\"$${WEBUI_ADMIN_USER}\", \"email\":\"$${WEBUI_ADMIN_EMAIL}\", \"password\":\"$${WEBUI_ADMIN_PASS}\"}")

        API_KEY=$(echo "$${SIGNUP_RESPONSE}" | jq -r '.token')

        echo "Received API_KEY: $${API_KEY}"

        JSON_TEMPLATE_PATH="/app/backend/open_webui/pipeline/template.json"
        PYTHON_FILE_PATH="/app/backend/open_webui/pipeline/"$${PIPE_FUNC_FILE}.py

        # Read the Python file and escape special characters for JSON
        PYTHON_CODE=$(jq -Rs . < "$${PYTHON_FILE_PATH}")

        # Read the template and replace placeholders
        DATA_RAW=$(jq --arg id "$${PIPE_FUNC_ID}" \
                      --arg name "$${PIPE_FUNC_NAME}" \
                      --arg desc "$${PIPE_FUNC_DESCRIPTION}" \
                      --argjson content "$${PYTHON_CODE}" \
                      '.id=$$id | .name=$$name | .meta.description=$$desc | .content=$$content' \
                      "$${JSON_TEMPLATE_PATH}")

        echo "Adding Pipe function to Open WebUI"
        curl -s -X POST "http://localhost:8080/api/v1/functions/create" \
          -H "Authorization: Bearer $${API_KEY}" \
          -H "Content-Type: application/json" \
          --data-raw "$${DATA_RAW}"

        # Keep the container running
        wait
    volumes:
      - webui.data:/app/backend/data
      - ${PWD}/webui/configs:/app/backend/open_webui/configs:ro
      - ${PWD}/webui/pipeline:/app/backend/open_webui/pipeline:ro
    networks:
      - internal

volumes:
  webui.data:
    name: owi-webui-data


networks:
  internal:
    name: owi-internal